name = "sport-data"
compatibility_date = "2024-12-02"

[site]
bucket = "./dist"
entry-point = "."

[build]
command = "npm run build"
publish = "dist"

# For client-side routing
[[routes]]
pattern = "/*"
script_name = "_worker.js"
